Repository codestates-seb/seb41_main_020, pull requests merged in 2023-01, with the labels that each got.

#13 [feat -> develop] 글로벌 ResponseDto 작성
  server/src/main/java/codestates/frogroup/indiego/global/dto/MultiResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/global/dto/PageInfo.java
  server/src/main/java/codestates/frogroup/indiego/global/dto/SingleResponseDto.java
Labels: ⚙️ Feat

#17 [Feat → Dev] mixin 작성 및 공통 스타일링 추가
  client/src/Components/Header.jsx
  client/src/Pages/Home.jsx
  client/src/assets/icon.svg
  client/src/assets/logo.svg
  client/src/styles/breakpoint.js
  client/src/styles/mixins.js
Labels: 🎨 Design

#18 [Feat -> Dev] Header 컴포넌트 html / css 레이아웃 작성
  client/src/Components/Header.jsx
  client/src/index.css
Labels: 🎨 Design

#22 [Feat → Dev] 공연 DTO 개발
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
Labels: ⚙️ Feat

#23 [Feat -> Dev] 스텁 데이터 작성
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/dto/ArticleDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/dto/MemberDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/dto/MemberProfileDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowComment.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: 📰 New File, ⚙️ Feat

#26 [Feat -> Dev] 스텁 데이터 및 컨트롤러 작성
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/Article.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: ☔️ Test

#28 [Feat → Dev] 회원 API Stub Data 응답
  server/src/main/java/codestates/frogroup/indiego/domain/member/controller/MemberController.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/Member.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/dto/MemberDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/dto/MemberProfileDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/enums/ProfileImage.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/mapper/MemberMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/repository/MemberRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: ☔️ Test

#34 [Feat -> Dev] 게시글 초기 세팅 작업
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/Article.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
Labels: 🎉 Initial Commit

#35 [Feat → Dev] 회원 컨트롤러 개발
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: ⚙️ Feat

#36 Feat/fe/kkb/board
  client/.eslintrc.json
  client/src/Components/OKButton.jsx
  client/src/Components/Pagination.jsx
  client/src/DummyData/BoardDummy.js
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board.jsx
  client/src/Pages/Boards/Post/PostCreate.jsx
  client/src/assets/Magnifier.svg
  client/src/assets/down.svg
  client/src/assets/heart.svg
  client/src/assets/left.svg
  client/src/assets/pen.svg
  client/src/assets/right.svg
  client/src/index.css
Labels: 🎨 Design

#38 [Feat -> Dev] 메인페이지 레이아웃 작성 및 팝업 작성 중
  client/src/Components/Main/Banner.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Button.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Carousels/MultipleItem.jsx
  client/src/Components/Main/Carousels/Renderer.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/Popups/Overlay.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Pages/Home.jsx
  client/src/assets/SeoulMap.svg
  client/src/assets/arrow.svg
  client/src/assets/search.svg
Labels: 🎨 Design

#39 [Feat -> Dev] Board 페이지 작성중
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Components/Editor.jsx
  client/src/Components/EditorView.jsx
  client/src/DummyData/AnswerDummy.js
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board.jsx
  client/src/Pages/Boards/Post/EXbackground.jsx
  client/src/Pages/Boards/Post/Post.jsx
  client/src/Pages/Boards/Post/PostCreate.jsx
Labels: 🎨 Design

#43 [Feat -> Dev] 커뮤니티 게시판 및 댓글 초기 로직 구현
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/Article.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/ArticleComment.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/ArticleCommentLike.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/ArticleLike.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/dto/ArticleCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/entity/dto/ArticleDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleCommentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentLikeRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleLikeRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleServiceImpl.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: ⚙️ Feat

#46 [Feat -> Rel] 초기 배포를 위한 병합
  .github/workflows/gradle.yml
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/Show.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: 🚀 Deploy

#50 [Feat -> Dev] 메인페이지 반응형 구현
  client/src/App.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItem.jsx
  client/src/Components/Main/Carousels/LongCarouselItemList.jsx
  client/src/Components/Main/Carousels/MultipleItem.jsx
  client/src/Components/Main/Popups/List.jsx
  client/src/Components/Main/Popups/ListItem.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/Popups/Overlay.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Pages/Home.jsx
Labels: 🎨 Design

#51 [Feat -> Rel] 배포를 위한 머지
  server/appspec.yml
  server/scripts/deploy.sh
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
Labels: 🚀 Deploy

#53 [Feat -> Dev] 티켓 판매 페이지 작성
  client/src/Components/Editor.jsx
  client/src/Components/OKButton.jsx
  client/src/Components/SearchBar.jsx
  client/src/DummyData/AnswerDummy.js
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board.jsx
  client/src/Pages/Boards/Post/EXbackground.jsx
  client/src/Pages/Boards/Post/Post.jsx
  client/src/Pages/Boards/Post/PostCreate.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: 🎨 Design

#55 [Feat -> Dev] #9 헤더 컴포넌트 레이아웃 작성완료
  client/package-lock.json
  client/package.json
  client/src/Components/Header.jsx
  client/src/Components/Main/Popups/Overlay.jsx
  client/src/Pages/Home.jsx
  client/src/assets/user.svg
  client/src/store/useNavbarStore.js
  client/src/utils/useWindowSize.js
Labels: 🎨 Design

#59 [Feat → Dev] 공연 판매, 예약 구현
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Pages/Tickets/TicketsDetail.jsx
  client/src/index.css
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/domain/common/embedding/Board.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/Show.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowBoard.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowComment.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowReservation.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowCommentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowReservationMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowReservationRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: ⚙️ Feat

#61 [Feat -> Dev] #32 날짜별 공연현황 팝업 작성중
  client/package-lock.json
  client/package.json
  client/src/Components/Header.jsx
  client/src/Components/Main/Carousels/LongCarouselItemList.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/List.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/Popups/Overlay.jsx
  client/src/Pages/Home.jsx
Labels: 🎨 Design, ⚙️ Feat

#57 [Feat → Dev] Security 작업 진행
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/config/RedisConfig.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/controller/MemberController.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/dto/MemberDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
  server/src/main/java/codestates/frogroup/indiego/global/redis/RedisDao.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/dto/TokenDto.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/filter/JwtVerificationFilter.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/jwt/TokenProvider.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/utils/ErrorResponder.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/utils/Responder.java
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: ⚙️ Feat

#64 [Feat -> Dev] #10 - searchbar 구현 완 및 분리 완 및 answerDummy 오타 수정
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Components/Board/SearchBar.jsx
  client/src/DummyData/AnswerDummy.js
  client/src/Pages/Boards/Board.jsx
Labels: 🎨 Design

#68 [Feat -> Dev] 캘린더 팝업 레이아웃 완료
  client/package-lock.json
  client/src/Components/Header.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
Labels: 🎨 Design, ⚙️ Feat

#70 [Feat -> Dev] 로그인 페이지 완료된 부분 PR합니다
  client/src/Components/TicketsDetail/TicketsDetailTapMenu.jsx
  client/src/Pages/Login.jsx
Labels: 🎨 Design, ⚙️ Feat

#71 [Feat -> Dev] Post 페이지 제외 한 반응형 작업 완료
  client/src/Components/Board/SearchBar.jsx
  client/src/Components/EditorView.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board.jsx
  client/src/Pages/Boards/Post/Post.jsx
  client/src/Pages/Boards/Post/PostCreate.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: 🎨 Design

#75 [Feat -> Dev] #74 티켓팅페이지 기본 레이아웃 작성 완료
  client/src/Components/Main/Button.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/DummyData/mainDummy.js
  client/src/Pages/Home.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/styles/mixins.js
Labels: 🎨 Design

#79 [Feat -> Dev] 회원가입 페이지 레이아웃 작성, 유효성 검사 기능 작업 완료 후 PR합니다
  client/src/Pages/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Pages/Signup/SignupPerformer.jsx
  client/src/assets/kakaoIcon.jpg
  client/src/assets/naverIcon.jpg
Labels: 🎨 Design, ⚙️ Feat

#83 [Feat → Dev] 공연 예약 서비스 로직 구현
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/MemberBookMark.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/MemberBookMarkController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowReservation.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowReservationMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/MemberBookMarkRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/MemberBookMarkService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: ⚙️ Feat

#85 [Feat -> Dev] 게시글 리팩토링 및 검색 기능 작성 중
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/dto/ArticleCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/dto/ArticleDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/dto/ArticleListResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/dto/ArticleSearchCondition.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleCommentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleLikeRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/global/stub/StubData.java
Labels: 🔨 refactoring, ⚙️ Feat

#90 [FeaT->Dev] Feat/fe/kkb/markup v5
  client/src/App.jsx
  client/src/Components/Board/Board/EditorView.jsx
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/OKButton.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Components/Pagination.jsx
  client/src/Components/SearchBar.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/Board/EXbackground.jsx
  client/src/Pages/Boards/BoardType/AdvertiseBoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoard.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/Pages/Boards/Post/PostEdit.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: 🎨 Design, ⚙️ Feat

#94 [Feat -> Dev] 맵 api 도입중
  client/public/index.html
  client/src/App.jsx
  client/src/Components/Footer.jsx
  client/src/Components/Header.jsx
  client/src/Pages/Search.jsx
  client/src/assets/github.svg
  client/src/assets/notion.png
  client/src/utils/useWindowSize.js
Labels: ⚙️ Feat

#89 [Feat -> Dev] 공연 후기 리팩토링
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowCommentController.java
Labels: 🔨 refactoring

#100 [Feat -> Dev] 게시글 리스트 조회 작성(좋아요순 미구현)
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/dto/ArticleListResponseDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/ArticleRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
Labels: ⚙️ Feat

#102 [Feat -> Dev] 오류 수정, 컴포넌트 분리, 우편 번호 api 도입
  client/package-lock.json
  client/package.json
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Board/TicketsCreate/Postcode.js
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: ⚙️ Feat

#109 [Feat -> Dev] 카카오 맵 api 클러스터 추가 및 오류 수정
  client/public/index.html
  client/src/DummyData/locationDummy.js
  client/src/Pages/Search.jsx
  client/src/assets/marker.svg
  client/src/index.js
  client/src/styles/MarkerOverlay.css
Labels: ⚙️ Feat

#111 [Feat -> Dev] Header 컴포넌트 로그인, 로그아웃 상태 분리 및 현재위치 기억 로직 작성
  client/src/Components/Header.jsx
Labels: 🎨 Design, ⚙️ Feat

#112 [Feat -> Dev] 프로필 수정 페이지 레이아웃, 반응형 웹 완료 후 PR
  client/src/App.jsx
  client/src/Pages/Profile/ProfileEdit.jsx
Labels: ⚙️ Feat

#114 [Feat -> Dev] 카테고리 선택, 시작 일, 모든 값 useState로 관리 완
  client/src/Components/Board/TicketsCreate/CategoryDropdown.jsx
  client/src/Components/Board/TicketsCreate/Postcode.js
  client/src/Components/Board/TicketsCreate/ReactDatePicker.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: ⚙️ Feat

#121 [Feat -> Dev] 커뮤니티 게시글 검색 및 조회 구현
  server/build.gradle
Labels: 🔨 refactoring, 📰 New File, ⚙️ Feat

#125 [Feat -> Dev] 닫기가 가능한 커스텀 오버레이 추가 및 호버 오버레이 수정
  client/src/Pages/Home.jsx
  client/src/Pages/Search.jsx
  client/src/styles/MarkerOverlay.css
Labels: 🎨 Design, ⚙️ Feat

#131 [Feat -> Dev] tanstack query, zustand 설정, 일부 css 수정
  client/package.json
  client/src/Components/Footer.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/BoardType/AdvertiseBoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoard.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/index.js
  client/src/store/boardListStore.js
  client/src/utils/ScrollTop.jsx
Labels: ⚙️ Feat

#133 [Feat -> Dev] 메인페이지 캐러셀 오토 스크롤링 구현
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItemList.jsx
  client/src/utils/useInterval.js
Labels: ⚙️ Feat

#135 [Feat -> Dev] 프로필 수정 페이지 내 동네 선택, 공연 상세 페이지 카카오맵 버튼 기능 구현
  client/.eslintrc.json
  client/src/Components/Main/Popups/SeoulMap.jsx
  client/src/Components/Profile/SelectProfileLocationModal.jsx
  client/src/Components/Profile/WithdrawModal.jsx
  client/src/Components/TicketsDetail/KakaoMapButton.jsx
  client/src/Pages/Profile/Profile.jsx
  client/src/Pages/Profile/ProfileEdit.jsx
  client/src/Pages/Profile/ProfilePerformer.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
  client/src/store/useSelectProfileLocationModalStore.js
  client/src/store/useSelectedProfileLocationStore.js
  client/src/store/useWithdrawModalStore.js
Labels: 🎨 Design, ⚙️ Feat

#137 [Feat -> Dev] BoardList, Board 컴포넌트 분리
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/BoardType/AdvertiseBoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoard.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/store/useAnswerListStore.js
  client/src/store/useBoardListStore.js
Labels: 🔨 refactoring

#129 [Feat -> Dev] 로그아웃 API 구현완료
  server/src/main/java/codestates/frogroup/indiego/domain/member/controller/MemberController.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
  server/src/main/java/codestates/frogroup/indiego/global/fileupload/AwsS3Service.java
Labels: ⚙️ Feat

#132 [Feat->Dev] 공연 판매글 이미지 업로드
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
Labels: ⚙️ Feat

#145 #127 - 스프링 시큐리티 배포환경 설정2
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/handler/OAuth2MemberSuccessHandler.java
Labels: 🚀 Deploy

#148 [Feat -> Dev] css 마무리 및 tanstack query 설정
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/store/useBoardListStore.js
Labels: 🎨 Design, ⚙️ Feat

#150 [Feat -> Dev] 회원가입 페이지 로직 구현 완료 후 PR
  client/src/Components/TicketsDetail/KakaoMapButton.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Pages/Signup/SignupPerformer.jsx
Labels: ⚙️ Feat

#165 [Feat->Dev] 공연 평균 별점
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowCommentDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowComment.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowCommentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowReservationRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
Labels: ⚙️ Feat

#186 [Feat->Dev] 로그인 로직 구현 중 리프레시 토큰이 쿠키에 담기지 않는 문제가 있어 수정 중
  client/src/Pages/Login.jsx
  client/src/Pages/Profile/Profile.jsx
  client/src/api/core/default.js
  client/src/store/useLoginStore.js
Labels: 🚑 Bug Fix

#196 [Feat -> Dev] 회원가입 시 이메일 전송 로직 구현
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/global/email/EmailSend.java
  server/src/main/java/codestates/frogroup/indiego/global/email/EmailSendImpl.java
  server/src/main/java/codestates/frogroup/indiego/global/email/EmailService.java
  server/src/main/java/codestates/frogroup/indiego/global/email/config/EmailConfig.java
  server/src/main/java/codestates/frogroup/indiego/global/email/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/codestates/frogroup/indiego/global/email/event/MemberRegistrationEventListener.java
  server/src/main/resources/templates/email-registration-member.html
Labels: 📰 New File, ⚙️ Feat

#199 [Feat -> Dev] 페이지네이션 작성
  client/src/App.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Components/Header.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/store/useBoardStore.js
Labels: ⚙️ Feat

#200 [Feat -> Dev] 메인 페이지 조회 및 공연 검색 조회 구현
  client/cert.pem
  client/key.pem
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItem.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/List.jsx
  client/src/Components/Main/Popups/ListItem.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Spinner.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/jsonserver/db.json
  client/src/jsonserver/routes.json
Labels: ⚙️ Feat

#198 [Dev -> Rel] 이메일 전송 및 공연 조회 에러 픽스
  client/cert.pem
  client/key.pem
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Components/Header.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItem.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/List.jsx
  client/src/Components/Main/Popups/ListItem.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Spinner.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/jsonserver/db.json
  client/src/jsonserver/routes.json
  client/src/store/useBoardStore.js
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowReservationRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/global/email/EmailSend.java
  server/src/main/java/codestates/frogroup/indiego/global/email/EmailSendImpl.java
  server/src/main/java/codestates/frogroup/indiego/global/email/EmailService.java
  server/src/main/java/codestates/frogroup/indiego/global/email/config/EmailConfig.java
  server/src/main/java/codestates/frogroup/indiego/global/email/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/codestates/frogroup/indiego/global/email/event/MemberRegistrationEventListener.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
  server/src/main/resources/templates/email-registration-member.html
Labels: 🔨 refactoring, 📰 New File, 🚑 Bug Fix, ⚙️ Feat

#201 [Feat->Dev] 공연 평균 별점
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ScoreRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
Labels: 🔨 refactoring

#204 [Feat->Dev] redis 적용
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ScoreRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/global/redis/RedisKey.java
Labels: 🔨 refactoring, ⚙️ Feat

#213 [Feat -> Dev] 로그인, 토큰 재발급, 로그아웃 로직 등 구현 후 PR
  client/cert.pem
  client/key.pem
  client/src/App.jsx
  client/src/Components/Header.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Profile/Profile.jsx
  client/src/Pages/Signup/SignupPerformer.jsx
  client/src/api/core/default.js
  client/src/store/useIsLoginStore.js
Labels: ⚙️ Feat

#228 [Feat->Dev] 공연로직 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/global/redis/RedisDao.java
Labels: 🚑 Bug Fix

#238 [Feat->Dev] 공연 수정 및 작성
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowReservationRepository.java
Labels: 🔨 refactoring, 🚑 Bug Fix

#241 [Feat -> Dev] 게시글 CRUD 및 공연 이미지 작업
  client/src/App.jsx
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Components/Header.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/api/core/image.js
  client/src/store/useBoardStore.js
Labels: ⚙️ Feat

#245 [Feat -> Dev] 회원 도메인 관련 수정
  server/src/main/java/codestates/frogroup/indiego/domain/member/dto/MemberDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/Member.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/mapper/MemberMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
Labels: 🔨 refactoring

#246 [Feat->Dev] 공연 수정 및 추가
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/MemberBookMarkService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/global/exception/ExceptionCode.java
Labels: 🔨 refactoring

#250 [Feat -> Dev] 게시판 좋아요 및 댓글 좋아요 수정 + data.sql 수정
  server/build.gradle
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleCommentService.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/resources/data.sql
Labels: 🔨 refactoring

#255 #248 - 게시판 댓글 좋아요 메서드 분리, 게시글 댓글 삭제 수정
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleCommentService.java
Labels: 🔨 refactoring

#261 [Feat -> Dev] 카카오맵 백엔드 로직 연결
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Header.jsx
  client/src/Components/Main/Banner.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItemList.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/List.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Search/KaKaoMap.jsx
  client/src/Components/Search/SearchPanel.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Search.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/index.css
  client/src/styles/MarkerOverlay.css
  client/src/utils/createMarker.js
  client/webpack.config.js
Labels: 🎨 Design, 🚑 Bug Fix, ⚙️ Feat

#263 [Feat -> Dev] 이미지 업로드 및 delete 기능
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Board/EditorView.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/api/core/imageHandler.js
Labels: ⚙️ Feat

#265 [Feat -> Dev] 이미지 작업 완료 및 게시글 삭제 작업 완
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Board/EditorView.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/api/core/imageHandler.js
Labels: ⚙️ Feat

#268 [Feat->Dev] #267 스크롤바 디자인 통일 안되는 이슈 해결
  client/src/Pages/Login.jsx
  client/src/index.css
Labels: 🎨 Design, 🚑 Bug Fix

#269 Revert "[Feat->Dev] #267 스크롤바 디자인 통일 안되는 이슈 해결"
  client/src/Pages/Login.jsx
  client/src/index.css
Labels: 🚑 Bug Fix

#272 [Feat -> Dev] 공연 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
Labels: 🚑 Bug Fix

#274 [Feat -> Dev] 로그인 페이지 데이터 복구 후 PR
  client/src/App.jsx
  client/src/Components/Main/Popups/SeoulMap.jsx
  client/src/Components/Profile/AllShowList.jsx
  client/src/Components/Profile/SelectProfileLocationModal.jsx
  client/src/Components/Profile/ShowItem.jsx
  client/src/Components/Profile/ShowList.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Profile/Profile.jsx
  client/src/Pages/Profile/ProfileEdit.jsx
  client/src/Pages/Profile/ProfilePerformer.jsx
  client/src/api/core/default.js
  client/src/store/useProfileDataStore.js
  client/src/store/useSelectedProfileLocationStore.js
Labels: ⚙️ Feat

#280 [Feat -> Dev] 게시글 수정
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleCommentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
Labels: 🔨 refactoring, 🚑 Bug Fix

#283 [Dev -> Rel] 게시판 수정 및 회원 테스트 추가
  client/src/App.jsx
  client/src/Components/Main/Popups/SeoulMap.jsx
  client/src/Components/Profile/AllShowList.jsx
  client/src/Components/Profile/SelectProfileLocationModal.jsx
  client/src/Components/Profile/ShowItem.jsx
  client/src/Components/Profile/ShowList.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Profile/Profile.jsx
  client/src/Pages/Profile/ProfileEdit.jsx
  client/src/Pages/Profile/ProfilePerformer.jsx
  client/src/api/core/default.js
  client/src/store/useProfileDataStore.js
  client/src/store/useSelectedProfileLocationStore.js
  server/src/main/java/codestates/frogroup/indiego/domain/article/controller/ArticleController.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/mapper/ArticleCommentMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustom.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/repository/querydsl/ArticleRepositoryCustomImpl.java
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/controller/MemberController.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/dto/LoginDto.java
  server/src/test/java/codestates/frogroup/indiego/IndieGoApplicationTests.java
  server/src/test/java/codestates/frogroup/indiego/domain/member/controller/MemberControllerTest.java
  server/src/test/java/codestates/frogroup/indiego/helper/MemberTestHelper.java
  server/src/test/java/codestates/frogroup/indiego/helper/StubData.java
Labels: 🚀 Deploy, 🚑 Bug Fix, ☔️ Test

#285 [Feat -> Dev] 유저 공연 예약 조회 반환값 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowReservationDto.java
Labels: 👀 misc

#291 [ Feat -> Dev ] 공연 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/dto/ShowDto.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/Show.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/entity/ShowBoard.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/mapper/ShowMapper.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/resources/data.sql
Labels: ⚙️ Feat

#299 [Feat -> Dev] cors 수정, 게시글 좋아요 수정
  server/src/main/java/codestates/frogroup/indiego/domain/article/service/ArticleService.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/jwt/TokenProvider.java
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
  server/src/main/resources/data.sql
Labels: 🔨 refactoring, 🚑 Bug Fix

#302 [Feat -> Dev] url변경 및 페이지 예외 처리
  client/package-lock.json
  client/package.json
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/assets/blueHeart.gif
  client/src/assets/yellowHeart.gif
Labels: 🔨 refactoring, 🚑 Bug Fix, ⚙️ Feat

#328 [Feat -> Dev] 버그 수정 및 위치 기반 기능 추가 + CSS 재배치
  client/public/index.html
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Footer.jsx
  client/src/Components/Header.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Button.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Carousels/Item.jsx
  client/src/Components/Main/Carousels/LongCarousel.jsx
  client/src/Components/Main/Carousels/LongCarouselItem.jsx
  client/src/Components/Main/Carousels/LongCarouselItemList.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/List.jsx
  client/src/Components/Main/Popups/ListItem.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Search/KaKaoMap.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/Search.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/index.css
  client/src/styles/MarkerOverlay.css
  client/src/utils/createMarker.js
  client/webpack.config.js
Labels: 🎨 Design, 🚑 Bug Fix, ⚙️ Feat

#335 [Feat -> Dev] 게시판별 올바른 정보 불러오기
  client/src/App.jsx
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoard.jsx
  client/src/Pages/Boards/BoardType/EmployBoardList.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: 🎨 Design, 🚑 Bug Fix, ⚙️ Feat

#333 [Feat -> Dev ] 공연 예외 처리 추가
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowReservationController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowReservationService.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
  server/src/main/java/codestates/frogroup/indiego/global/security/config/SecurityConfiguration.java
Labels: ⚙️ Feat

#348 [Feat -> Dev] 버그 수정 + 캐러셀 무한 스크롤 + 404 추가
  client/public/index.html
  client/src/Components/Footer.jsx
  client/src/Components/Header.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Carousels/CarouselItemList.jsx
  client/src/Components/Main/Popups/DatePopup.jsx
  client/src/Components/Main/Popups/LocationPopup.jsx
  client/src/Components/Search/KaKaoMap.jsx
  client/src/Components/Search/SearchPanel.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/NotFound.jsx
  client/src/assets/NotFound.svg
  client/src/assets/NotFound_animate.svg
Labels: 🎨 Design, 🚑 Bug Fix, ⚙️ Feat

#349 [Feat -> Dev] boardEdit 페이지 및 마무리 css 작업
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/BoardListItem/BoardListItem.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/BoardType/AdvertiseBoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoardList.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: 🎨 Design, ⚙️ Feat

#350 [Deat -> Dev] 공연 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
Labels: 👀 misc

#353 [Feat -> Dev] 공연 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowCommentController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowCommentRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowCommentService.java
Labels: 👀 misc

#356 [Feat -> Dev] Board 페이지 Tickets페이지 콘솔 제거
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/PageNation.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/BoardType/AdvertiseBoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoardList.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: 🔥 delete

#357 [Feat -> Dev] 404 페이지 배치 수정
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Pages/NotFound.jsx
  client/src/Pages/Search.jsx
Labels: 🎨 Design

#361 [Feat -> Dev] 알림창 설정
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: ⚙️ Feat

#362 [Feat -> Dev] 모바일 Board 페이지 css 수정
  client/src/Pages/Boards/Board/Board.jsx
Labels: 🎨 Design

#371 [Feat -> Dev] 불필요한 코드 삭제 및 주석 정리
  client/src/Components/Board/Answer/AnswerItem.jsx
  client/src/Components/Board/Answer/AnswerList.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Components/Board/BoardList/Dropdown.jsx
  client/src/Components/Board/BoardList/SearchBar.jsx
  client/src/Components/Board/TicketsCreate/CategoryDropdown.jsx
  client/src/Components/Board/TicketsCreate/ReactDatePicker.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/Board.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/Board/EXbackground.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: 🔥 delete, ⚙️ Feat

#372 [Feat -> Dev] 마무리 작업
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: ⚙️ Feat

#373 [Feat -> Dev] 로그인 하지 않을 시 게시글 생성 페이지 접근 불가
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
Labels: ⚙️ Feat

#377 [Feat -> Dev] 요청게시판 -> 초청게시판 으로 변경
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
Labels: 👀 misc

#378 [Feat->Dev] 공연 상세 페이지 후기 관련 오류 수정, 마이페이지 내 공연 목록 레이아웃 수정, 콘솔 로그 삭제 후 pr
  client/src/Components/Profile/AllShowList.jsx
  client/src/Components/Profile/AllShowListPerformer.jsx
  client/src/Components/Profile/ShowItem.jsx
  client/src/Components/Profile/ShowItemPerformer.jsx
  client/src/Components/Profile/ShowListPerformer.jsx
  client/src/Components/TicketsDetail/ReviewItem.jsx
  client/src/Components/TicketsDetail/TicketsDetailTapMenu.jsx
  client/src/Components/TicketsDetail/TicketsDetailTapReview.jsx
  client/src/Pages/Tickets/TicketsDetail.jsx
Labels: 🚑 Bug Fix

#380 [Feat -> Dev] 데이트피커 예외 설정
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
Labels: ⚙️ Feat

#381 [Feat -> Dev] 데이트피커 날짜 오류, member 페이지 테마 컬러 안 바뀌는 오류 수정 후 pr
  client/src/Components/Board/TicketsCreate/ReactDatePicker.jsx
  client/src/Pages/Members.jsx
Labels: 🚑 Bug Fix

#384 [Feat -> Dev] OAuth2 문제수정
  server/src/main/java/codestates/frogroup/indiego/domain/member/entity/Member.java
  server/src/main/java/codestates/frogroup/indiego/domain/member/service/MemberService.java
  server/src/main/java/codestates/frogroup/indiego/global/security/auth/oauth/OAuthUserProfile.java
Labels: 🚑 Bug Fix

#387 [Feat -> Dev]게시판 분류 aside 수정 완
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Aside/MobileAside.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
Labels: ⚙️ Feat

#390 [Feat -> Dev] 공연 조회 수정
  server/src/main/java/codestates/frogroup/indiego/domain/show/controller/ShowController.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/repository/ShowRepository.java
  server/src/main/java/codestates/frogroup/indiego/domain/show/service/ShowService.java
Labels: 👀 misc

#393 [Feat->Dev] 프로필 수정 페이지 오류 해결 후 pr
  client/src/Pages/Profile/ProfileEdit.jsx
Labels: 🚑 Bug Fix

#396 [Feat -> Dev] 메인, 공연 찾기 레이아웃 버그 수정
  client/public/favicon.ico
  client/public/icon.svg
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/Components/Header.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
  client/src/Components/Main/Popups/Calendar.jsx
  client/src/Components/Main/SearchBar.jsx
  client/src/Components/Ticktes/CardItem.jsx
  client/src/Components/Ticktes/ItemList.jsx
  client/src/Components/Ticktes/SearchOptions.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Search.jsx
  client/src/Pages/Tickets/Tickets.jsx
  client/src/styles/MarkerOverlay.css
Labels: 🚑 Bug Fix

#397 [Feat -> Dev] 게시판 aside 수정 완료
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Components/Board/BoardCreate/Editor.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Tickets/TicketsCreate.jsx
  client/src/Pages/Tickets/TicketsEdit.jsx
  client/src/index.css
Labels: 🚑 Bug Fix

#398 [Feat -> Dev] 공연 상세페이지 공연 정보 컨테이너 css 오류 수정 후 pr
  client/src/Pages/Tickets/TicketsDetail.jsx
  client/src/api/core/default.js
Labels: 🚑 Bug Fix

#399 [Feat -> Dev] 게시글 수정시 대표이미지 이상현상 해결
  client/src/Components/Board/BoardCreate/CreateDropdown.jsx
  client/src/Pages/Boards/Aside/Aside.jsx
  client/src/Pages/Boards/Board/BoardCreate.jsx
  client/src/Pages/Boards/Board/BoardEdit.jsx
  client/src/Pages/Boards/Board/BoardList.jsx
  client/src/Pages/Boards/BoardType/AdvertiseBoardList.jsx
  client/src/Pages/Boards/BoardType/EmployBoardList.jsx
  client/src/Pages/Boards/BoardType/RequestBoardList.jsx
  client/src/Pages/Boards/BoardType/ReviewBoardList.jsx
  client/src/index.css
Labels: 🚑 Bug Fix

#400 [Feat -> Dev] 보드, 캐러셀 데이터 없을 시 null info 추가
  client/public/index.html
  client/src/Components/Header.jsx
  client/src/Components/Main/Boards/Board.jsx
  client/src/Components/Main/Boards/Boards.jsx
  client/src/Components/Main/Carousels/Carousel.jsx
Labels: 🚑 Bug Fix
